export const SELECT_SEATS_FOR_REGISTER = "SELECT_SEATS_FOR_REGISTER"
export const UPDATED_SEATS = 'UPDATED_SEATS'
export const REMOVE_SELECTED_SEAT_FOR_REGISTER = "REMOVE_SELECTED_SEATS_FOR_REGISTER"

export const TEMP_REMOVE_SEATS = 'TEMP_REMOVE_SEATS'
export const BOOKED_SEATS = 'BOOKED_SEATS'