export const TODAY_SHOWS = "TODAY_SHOWS"
export const ONLINE_USERS = "ONLINE_USERS"
export const SEATS_RESERVATION_ONGOING = 'SEAT_RESERVATION_ONGOING'
export const SHOW_CREATED_MESSAGE = "SHOW_CREATED_MESSAGE"
export const SEND_MESSAGE_QUEUE = 'SEND_MESSAGE_QUEUE'
export const SEND_NOTICATIONS = 'SEND_NOTIFICATIONS'
